---

#- name: Configure SSH
#  vars_files:
#    - secrets.yml
#  user:
#    name: root
#    key: "{{ hertzner_ssh_key }}"

- name: Install Required Packages
  vars:
    ansible_fxserver_url: "{{ ansible_fxserver_url }}"
  package:
    name:
      - curl
      - wget
      - unzip
      - tar
      - make
      - automake
      - gcc-c++
      - git
      - glibc-devel
    state: present
  when: ansible_pkg_mgr == 'dnf' or ansible_pkg_mgr == 'yum'

- name: Create directory for FXServer
  file:
    path: /opt/FXServer/server
    state: directory
  

- name: Download FXServer archive
  get_url:
    url: "{{ ansible_fxserver_url }}"
    dest: /opt/FXServer/server/fx.tar.xz

- name: Extract FXServer archive
  unarchive:
    src: /opt/FXServer/server/fx.tar.xz
    dest: /opt/FXServer/server
    remote_src: yes
    creates: /opt/FXServer/server/run.sh

